### ISSUE TITLE
`waicOcc` returns `Inf`

### ISSUE THREAD

**Issue by abfleishman** [doserjef/spOccupancy#21]
I have a dataset with 2 years of data for American Kestrel collected with AudioMoth acoustic recorders and analyzed using BirdNET.  The detection history for the summer is below.

![image](https://user-images.githubusercontent.com/9219852/221654816-b843ac91-3495-43fc-b3f3-ba4208eab945.png)

I have tried modeling with various covariates, and each model when running the waicOcc returns `Inf` for `WAIC` and `-Inf` for `elpd`.  The model seems to have converged (r-hat <1.05) for the other 20 species I am working the waicOcc function works as expected.  The model is attached. 

[model.zip](https://github.com/doserjef/spOccupancy/files/10843008/model.zip)

I am not sure if this is a bug or if I have a data problem that I do not understand.  I would love to hear your thoughts on how to troubleshoot?

```r
library(spOccupancy)
m<- readRDS("model.rds")

summary(m)

    Call:
    tPGOcc(occ.formula = ~1 + fire + year + (1 | site_effect), det.formula = ~1 + scale(doy) + scale(effort) + 
        I(scale(doy)^2) + (1 | site_effect), data = spT_tidy, inits = spT_tidy.inits, priors = spT_tidy.priors, 
        n.batch = n.batch, batch.length = batch.length, n.omp.threads = 5, ar1 = ar1, n.report = 50, n.burn = n.burn, 
        n.thin = n.thin, n.chains = n.chains)
    
    Samples per Chain: 20000
    Burn-in: 15000
    Thinning Rate: 10
    Number of Chains: 4
    Total Posterior Samples: 2000
    Run Time (min): 3.8595
    
    Occurrence (logit scale): 
                    Mean     SD    2.5%     50%  97.5%   Rhat  ESS
    (Intercept)   1.7336 0.9625 -0.0786  1.6878 3.7216 1.0032 1827
    fireunburned  1.5672 0.8717 -0.0834  1.5371 3.3343 1.0051 2000
    year         -0.6776 0.6131 -1.8590 -0.6777 0.5264 1.0048 2088
    
    Occurrence Random Effect Variances (logit scale): 
                  Mean     SD   2.5%    50%   97.5%  Rhat ESS
    site_effect 4.0451 6.2961 0.0872 2.1473 19.2739 1.052 367
    
    Detection (logit scale): 
                       Mean     SD    2.5%     50%   97.5%   Rhat  ESS
    (Intercept)     -3.9088 0.2238 -4.3553 -3.9026 -3.4764 1.0155  554
    scale(doy)      -0.2068 0.0569 -0.3193 -0.2060 -0.0957 1.0009 2000
    scale(effort)   10.5621 0.6435  9.3469 10.5475 11.8397 1.0156  459
    I(scale(doy)^2) -0.0585 0.0589 -0.1692 -0.0594  0.0575 1.0015 2133
    
    Detection Random Effect Variances (logit scale): 
                 Mean     SD   2.5%    50%  97.5%  Rhat  ESS
    site_effect 0.821 0.2858 0.4219 0.7658 1.5407 1.014 1305

waicOcc(m)

    elpd       pD     WAIC 
    -Inf 55.41925      Inf

**Comment by doserjef** [comment]
Hi Abram, 

This is interesting, thanks for sharing. I don't see any immediate problem from the model object. Can you email me (doserjef@msu.edu) the full script and the necessary data you use to fit the model so I can play around with it?

Thanks,

Jeff

**Comment by doserjef** [comment]
We determined the problem had to do with the `effort` variable that was included on the detection portion of the model. As shown in the above output, the covariate effect of `effort` was estimated to be very positive. The particular problem arose in this case because a large majority of the surveys had the same (or very similar) amount of effort, and there were only a few surveys that had very low effort. For the surveys with very low effort, detection probability was estimated to be essentially 0. However, there were a couple occasions where the species was observed at some of these low effort sites, which led to a conflict with the estimated detection probability of 0. This is why the WAIC returned as `Inf`. The issue was resolved by removing the sampling days that had 25% or 50% of the expected amount of effort.
