### ISSUE TITLE
c++ error: dpotrf failed in sfMsPGOcc

### ISSUE THREAD

**Issue by zaarakidwai** [doserjef/spOccupancy#24]
I am trying to calculate multi species occupancy with package spOccupancy. However, even after preparing my data for the analysis, I am unable to run the model as the error keeps popping up. "c++ error: dpotrf failed"
I had "julian date" in the data and I thought maybe that was causing issues so I removed it. My code looks like this 

out <- sfMsPGOcc(occ.formula = ~ scale(elevation)+ I(scale(elevation^2)) + scale(slope), 
                 det.formula = ~ scale(efforts), 
                 data = data,
                 n.batch = 400, 
                 tuning = list(phi = 2.5),
                 batch.length = 25,
                 n.thin = 10, 
                 n.burn = 5000, 
                 n.chains = 1,
                 NNGP = TRUE,
                 n.factors = 4,
                 n.neighbors = 5,
                 n.omp.threads = 1,
                 cov.model = 'exponential',
                 n.report = 10)

When I add scale (julian date) in the detection covariates, this error shows up "Error in as.vector(x, mode) :  cannot coerce type 'closure' to vector of type 'any'"

Not sure what the issue is but I am unable to run the model at all. I tried using all the solutions mentioned in issue#22 but it didn't help. I would appreciate any help in this regard.

**Comment by doserjef** [comment]
Hi Zaara, 

I quickly looked at the code/data you emailed me and I believe the "dpotrf" error is happening because you have some sites in the data that have the same coordinates. To fit a spatial model in spOccupancy, each site has to have it's own unique set of coordinates. Take a look at how you are generating the "coords" matrix and see if there is an issue that is resulting in a few of the sites having the same spatial coordinates. I am going to close this issue here as I believe it is related to data formatting and not an error with the package itself, and we can continue to communicate via email. I will open this back up if we uncover a problem with the package.
