### ISSUE TITLE
error in prediction: cannot allocate vector of size xx Gb

### ISSUE THREAD

**Issue by talimenger** [doserjef/spOccupancy#29]
Hi Jeff,

First, thanks for this really nice work on this R package. I am running a multi-species spatial occupancy model, however, when I get to the prediction step I cannot generate the prediction because of this error: cannot allocate vector of size xx Gb. Do you have any idea about what could have been causing this issue? I have 12 species in 120 sites with ~20 occasions and I am trying to predict for a huge number of locations (>100000). But the error still occurs when I use a lot less locations for prediction. Sorry for bothering you with that.

Thank you very much for your attention.

**Comment by doserjef** [comment]
Hello!

The size of the prediction objects for a multi-species spatial occupancy model is determined by three things: 

1. Number of species: in your case, 12 is pretty modest, so this probably isn't the problem. 
2. Number of prediction locations (not the problem if it's still giving an error with only a small number of prediction locations)
3. Number of MCMC samples saved from the model

It's likely this third component that's giving you the problem. The `predict()` function will generate a prediction for each species at each site for each MCMC sample, so if you saved a large number of samples (e.g., 10,000), the resulting objects can be pretty big. So, I'd suggest reducing the number of samples you save to try and reduce the size of the objects. This may require you to run the initial models for a longer period of time and have a higher thinning rate in order to achieve convergence. 

I'll also mention that when you go to do prediction, you may not be able to predict across all of those locations at one time, even after reducing the number of saved MCMC samples. In other words, you will probably have to do the prediction piece by piece (e.g., 1000 or even 100 locations at a time depending on how much RAM you're working with on your computer).

Let me know if that doesn't help or if I can clarify anything. 

Jeff

**Comment by talimenger** [comment]
Hello, 

Thanks a lot for this quick and careful answer. It helped me a lot to understand the problem. Both the higher tinning and splitting the prediction in parts seems to be working to address my issue. Now I am just working to find a good balance between these two things. So far I am being able to make prediction for 10000 locations at a time. Thanks again :)

Talita.
