### ISSUE TITLE
Occurrence covariates that vary by site and time (replicate)

### ISSUE THREAD

**Issue by DEHewitt** [doserjef/spOccupancy#33]
Hi,

I am beginning to write code to fit some models where I integrate multiple datasets and have covariates on the occurrence probability that vary by site and time (which is analogous to replicate in my case). I couldn't tell if this was currently supported, but is it possible to fit an `intPGOcc()` or `spIntPGOcc()` where `occ.covs` is formatted as a site x replicate matrix (similar to `det.covs`) or are there plans to develop integrated versions of `tPGOcc()` and `stPGOcc()`? Ultimately, we may also be interested in seasonal trends too...

Thanks!

**Comment by doserjef** [comment]
Hi @DEHewitt,

Thanks for the note! For single-season occupancy models, it's required that the occupancy state does not change over the replicates. This is the "closure assumption" that occupancy models are based on in order to separately estimate occupancy probability from detection probability. So for all single-season models (including `intPGOcc()` and `spIntPGOcc()` it's not possible to allow the occupancy covariates to vary over the replicates. Adding in integrated versions of the multi-season models is something on the todo list, but it will likely be at least a few months before I get around to that. 

I'm going to go ahead and close this issue, but feel free to reach out if I can help with anything else. 

Jeff

**Comment by DEHewitt** [comment]
Thanks for your fast response. Ah, I see. I must've misunderstood somewhere... Perhaps you can guide me in the right direction. 

I have data that was collected at multiple sites (beaches) over a period of ~20 years. On any given day, a site is visited and a single presence/absence survey is conducted (i.e., no replication within a visit), but it is possible for multiple beaches to be visited on the same day. I am interested in the effects of wind speed and direction (which vary by site and between days) and orientation of a site (which only varies by site) on occurrence probability. Is it possible to fit a model with `spOccupancy` that addresses this question?

**Comment by doserjef** [comment]
Hi @DEHewitt,

Thanks for the note and clarifying the data set. Yes, that does sound to me like a situation where you would have to fit a single-visit occupancy model. You could do this in spOccupancy using the multi-season models (`tPGOcc()` and `stPGOcc()`) and using days as the primary time periods. I will give a bit of caution here though. Single-visit occupancy models can be pretty sensitive to some of the parametric assumptions used in the model, and if those are broken (which we don't know with true data sets), estimates of occupancy probability can be unreliable. I have a paper in review on this topic, so if you're interested feel free to send me an email (doserjef@msu.edu) and I can send it to you. If there are any beaches where the site is visited on multiple days, then that would greatly help in separately estimating detection probability from occupancy probability and making inferences more robust to breaking assumptions of the modeling framework.

Cheers,

Jeff

**Comment by DEHewitt** [comment]
Thanks for the response @doserjef - I'll pick this conversation up via email. Just FYI I'm in Australia, hence the time difference in replies you may be noticing.
