### ISSUE TITLE
About bad posterior predictive results of msPGOcc

### ISSUE THREAD

**Issue by RachHus** [doserjef/spOccupancy#44]
Hi Jeff,

I am currently building multispecies occupancy models by using msPGOcc and have encountered an issue.
Even though I got good convergence indicaters regarding Rhat and ESS, the posterior predictive checks (ppcocc, group=1) are showing unexcpectedly low p-values for a few common species.
Can this kind of situation arise even when a model shows good convergence? 
What aspects should I particularly consider or investigate first to solve this problem?

Regards,
Francis

**Comment by doserjef** [comment]
Hi Francis, 

Apologies for the delay. The concepts of convergence and posterior predictive checks are two separate things. Convergence assessments look at whether or not the Bayesian model has converged, giving you an indication if you can start to interpret the model results or if you have to run the model for longer. Posterior predictive checks, on the other hand, assess whether or not your model is a good representation of the data that you have. Convergence assessments do not give any indication on whether the model is actually a good representation of the data set. So, yes, a model can certainly converge while having bad Bayesian p-values or showing some other form of bad model fit. 

A lack of model fit can happen for a variety of reasons. I encourage you to further explore the output from the posterior predictive checks function, doing something similar to what I showed in the introductory vignette, to see if there are certain data points that are causing the bad Bayesian p-values. I can't give much general advice on why the model may not fit well for your example: it is all dependent on the specific data set and the covariates/random effects that you have included in the model. If there is extra variability in occupancy probability and/or detection probability for some species in your data set that your model is not accounting for, then this could be causing the issue, in which case you may want to think about additional covariates you think may be causing this or including random effects (either spatial random effects in the occupancy portion or some sort of unstructured random effects in the detection component of the model). 

Hope that helps! I'm going to go ahead and close this issue since it doesn't directly relate to a problem with the software and rather is on interpreting the results.

Jeff
