### ISSUE TITLE
Error in ppcOcc (Function for performing posterior predictive checks)

### ISSUE THREAD

**Issue by Xuletajr** [doserjef/spOccupancy#7]
Dear Jeff,

I am fitting some single-species occupancy models (both spatial and non-spatial). However, I am facing some issues with an error in Error in "ppcOcc" function (Function for performing posterior predictive checks) for both spatial and non-spatial models . I've tried for more than one species and error persisted. 

The function has shown the following error, it doesn't matter which "fit.stat" I choose to use in the posterior predictive check:

_Error in `[<-`(`*tmp*`, names.long, , value = y.rep.samples) : 
  subscript out of bounds
In addition: There were 50 or more warnings (use warnings() to see the first 50)_

I am looking forward to your response. 

Best regards,

**Comment by doserjef** [comment]
Hi José, 

Thanks for posting this and for the info about the error. I'm not totally sure by just looking at that error, but it might be associated with having missing covariate values at sites/visits where you do have the actual detection-nondetection data. The package won't impute missing covariate values at locations/visits where you have detection-nondetection data, and it currently doesn't give any informative warning or error message about it (which I'm changing in the next version). It's fine to have corresponding missing values in the detection-nondetection data and the detection covariates (which happens if you don't have the same number of repeat visits for each site), it's just when they don't line up that there is a problem. Can you check your `det.covs` and `occ.covs` objects in the list of data that you send into the model fitting function and see if you have any missing values at sites (or site/visit combinations) where you do have detection-nondetection data (i.e., the corresponding value in `y` is not `NA`)? If so, you can either (1) impute the problematic covariate values in some way (i.e., just set it to the mean) or (2) set the corresponding value in `y` to NA, and then fit the model again and do the posterior predictive check. If this isn't the problem, can you email me (doserjef@msu.edu) a reproducible example? 

Thanks,

Jeff

**Comment by Xuletajr** [comment]
Hi Jeff,

Thank you very much for your useful reply. Yes, I have missing values in the visit occasions caused by unbalanced visits to sampling sites. As you suggested, the "ppcOcc" function works when I used another data set without missing values. 

Best,

**Comment by PabloQuilesTundidor** [comment]
Dear Jeff
I'm also fitting some single-species and multi-species occupancy models (both spatial and non-spatial) and I've encounter the same error. However I've checked and I don't have missing covariate values at sites/visits where I have detection-nondetection data. Moreover I have other issues running some of the multi-species model. Our data comes from a trail-camera proyect with aprox 150 sites, but using only 50 cameras in 30 days periods (and then moving the cameras to the next 50 sites). The resulting occupancy matrix covers all 150 sites during 3 months, but with a lot of NAs. I suppect thats the issue but I'm not sure. Would it be possible for you to check those errors?
Thank you in advance
Best regards
Pablo

**Comment by doserjef** [comment]
Hi Pablo, 

Thanks for the note and for taking a look through the previous issues to troubleshoot. Sorry that you're running into these problems. First thing I'll mention is that you may need to reinstall the latest version of spOccupancy if you are running the models with an older version, which you can do with `install.packages('spOccupancy')`. In particular, there was a similar bug encountered in Issue #11 that may explain what's going on, which I fixed in the most recent version of spOccupancy on CRAN. See my answer to that question. If you have the latest version of spOccupancy installed and you're still running into errors, then could you send me your data set via email and I'll take a look to try and see what's going on? 

Thanks,

Jeff
